version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - pwd
      - whoami
      - ls -a
      - ls -asl
      - cd HelloWorldFunction
      - mvn clean package
      - chmod -R 777 ./
      - cd ..
      - ls -asl
      - export BUCKET=codepipeline-ap-northeast-1-679695920619
      - sam package --template-file template.yaml --s3-bucket $BUCKET --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml